# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-24 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0002_auto_20200524_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='my_image',
            field=models.ImageField(default='image.jpg', upload_to='gallery/'),
        ),
    ]
