# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-24 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0003_image_my_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='my_image',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
